apiVersion: v1
kind: Service
metadata:
  name: spartapointswebservice
  labels:
    example: spartapointswebservice
  annotations:
    auth.istio.io/8017: NONE
spec:
  ports:
  - name: http
    port: 8017
  selector:
    example: spartapointswebservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spartapointswebservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        example: spartapointswebservice
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: hackergil/spartapoints:latest
        imagePullPolicy: Always
        name: spartapointswebservice
        ports:
        - name: http
          containerPort: 8017
